compile: build run

build:
	gcc ./src/main.c \
    	-o ./out/game.exe \
		-l SDL3 \
		-I C:\Libraries\SDL3-3.2.6\x86_64-w64-mingw32\include \
		-L C:\Libraries\SDL3-3.2.6\x86_64-w64-mingw32\lib

run:
	./out/game.exe

